// This file was generated automatically by the Snowball to C# compiler

#pragma warning disable 0164
#pragma warning disable 0162

namespace Snowball
{
    using System;
    using System.Text;
    
    ///<summary>
    ///  This class was automatically generated by a Snowball to Java compiler 
    ///  It implements the stemming algorithm defined by a snowball script.
    ///</summary>
    /// 
    [System.CodeDom.Compiler.GeneratedCode("Snowball", "0.0.0")]
    public partial class RomanianStemmer : SnowballStemmer
    {
        private bool B_standard_suffix_removed;
        private int I_p2;
        private int I_p1;
        private int I_pV;

        private static int[] g_v = { 17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 32, 0, 0, 4 };

        private readonly Among[] a_0;
        private readonly Among[] a_1;
        private readonly Among[] a_2;
        private readonly Among[] a_3;
        private readonly Among[] a_4;
        private readonly Among[] a_5;

        public RomanianStemmer()
        {
            a_0 = new[] 
            {
                new Among("", -1, 3),
                new Among("I", 0, 1),
                new Among("U", 0, 2)
            };

            a_1 = new[] 
            {
                new Among("ea", -1, 3),
                new Among("a\u00C5\u00A3ia", -1, 7),
                new Among("aua", -1, 2),
                new Among("iua", -1, 4),
                new Among("a\u00C5\u00A3ie", -1, 7),
                new Among("ele", -1, 3),
                new Among("ile", -1, 5),
                new Among("iile", 6, 4),
                new Among("iei", -1, 4),
                new Among("atei", -1, 6),
                new Among("ii", -1, 4),
                new Among("ului", -1, 1),
                new Among("ul", -1, 1),
                new Among("elor", -1, 3),
                new Among("ilor", -1, 4),
                new Among("iilor", 14, 4)
            };

            a_2 = new[] 
            {
                new Among("icala", -1, 4),
                new Among("iciva", -1, 4),
                new Among("ativa", -1, 5),
                new Among("itiva", -1, 6),
                new Among("icale", -1, 4),
                new Among("a\u00C5\u00A3iune", -1, 5),
                new Among("i\u00C5\u00A3iune", -1, 6),
                new Among("atoare", -1, 5),
                new Among("itoare", -1, 6),
                new Among("\u00C4\u0083toare", -1, 5),
                new Among("icitate", -1, 4),
                new Among("abilitate", -1, 1),
                new Among("ibilitate", -1, 2),
                new Among("ivitate", -1, 3),
                new Among("icive", -1, 4),
                new Among("ative", -1, 5),
                new Among("itive", -1, 6),
                new Among("icali", -1, 4),
                new Among("atori", -1, 5),
                new Among("icatori", 18, 4),
                new Among("itori", -1, 6),
                new Among("\u00C4\u0083tori", -1, 5),
                new Among("icitati", -1, 4),
                new Among("abilitati", -1, 1),
                new Among("ivitati", -1, 3),
                new Among("icivi", -1, 4),
                new Among("ativi", -1, 5),
                new Among("itivi", -1, 6),
                new Among("icit\u00C4\u0083i", -1, 4),
                new Among("abilit\u00C4\u0083i", -1, 1),
                new Among("ivit\u00C4\u0083i", -1, 3),
                new Among("icit\u00C4\u0083\u00C5\u00A3i", -1, 4),
                new Among("abilit\u00C4\u0083\u00C5\u00A3i", -1, 1),
                new Among("ivit\u00C4\u0083\u00C5\u00A3i", -1, 3),
                new Among("ical", -1, 4),
                new Among("ator", -1, 5),
                new Among("icator", 35, 4),
                new Among("itor", -1, 6),
                new Among("\u00C4\u0083tor", -1, 5),
                new Among("iciv", -1, 4),
                new Among("ativ", -1, 5),
                new Among("itiv", -1, 6),
                new Among("ical\u00C4\u0083", -1, 4),
                new Among("iciv\u00C4\u0083", -1, 4),
                new Among("ativ\u00C4\u0083", -1, 5),
                new Among("itiv\u00C4\u0083", -1, 6)
            };

            a_3 = new[] 
            {
                new Among("ica", -1, 1),
                new Among("abila", -1, 1),
                new Among("ibila", -1, 1),
                new Among("oasa", -1, 1),
                new Among("ata", -1, 1),
                new Among("ita", -1, 1),
                new Among("anta", -1, 1),
                new Among("ista", -1, 3),
                new Among("uta", -1, 1),
                new Among("iva", -1, 1),
                new Among("ic", -1, 1),
                new Among("ice", -1, 1),
                new Among("abile", -1, 1),
                new Among("ibile", -1, 1),
                new Among("isme", -1, 3),
                new Among("iune", -1, 2),
                new Among("oase", -1, 1),
                new Among("ate", -1, 1),
                new Among("itate", 17, 1),
                new Among("ite", -1, 1),
                new Among("ante", -1, 1),
                new Among("iste", -1, 3),
                new Among("ute", -1, 1),
                new Among("ive", -1, 1),
                new Among("ici", -1, 1),
                new Among("abili", -1, 1),
                new Among("ibili", -1, 1),
                new Among("iuni", -1, 2),
                new Among("atori", -1, 1),
                new Among("osi", -1, 1),
                new Among("ati", -1, 1),
                new Among("itati", 30, 1),
                new Among("iti", -1, 1),
                new Among("anti", -1, 1),
                new Among("isti", -1, 3),
                new Among("uti", -1, 1),
                new Among("i\u00C5\u009Fti", -1, 3),
                new Among("ivi", -1, 1),
                new Among("it\u00C4\u0083i", -1, 1),
                new Among("o\u00C5\u009Fi", -1, 1),
                new Among("it\u00C4\u0083\u00C5\u00A3i", -1, 1),
                new Among("abil", -1, 1),
                new Among("ibil", -1, 1),
                new Among("ism", -1, 3),
                new Among("ator", -1, 1),
                new Among("os", -1, 1),
                new Among("at", -1, 1),
                new Among("it", -1, 1),
                new Among("ant", -1, 1),
                new Among("ist", -1, 3),
                new Among("ut", -1, 1),
                new Among("iv", -1, 1),
                new Among("ic\u00C4\u0083", -1, 1),
                new Among("abil\u00C4\u0083", -1, 1),
                new Among("ibil\u00C4\u0083", -1, 1),
                new Among("oas\u00C4\u0083", -1, 1),
                new Among("at\u00C4\u0083", -1, 1),
                new Among("it\u00C4\u0083", -1, 1),
                new Among("ant\u00C4\u0083", -1, 1),
                new Among("ist\u00C4\u0083", -1, 3),
                new Among("ut\u00C4\u0083", -1, 1),
                new Among("iv\u00C4\u0083", -1, 1)
            };

            a_4 = new[] 
            {
                new Among("ea", -1, 1),
                new Among("ia", -1, 1),
                new Among("esc", -1, 1),
                new Among("\u00C4\u0083sc", -1, 1),
                new Among("ind", -1, 1),
                new Among("\u00C3\u00A2nd", -1, 1),
                new Among("are", -1, 1),
                new Among("ere", -1, 1),
                new Among("ire", -1, 1),
                new Among("\u00C3\u00A2re", -1, 1),
                new Among("se", -1, 2),
                new Among("ase", 10, 1),
                new Among("sese", 10, 2),
                new Among("ise", 10, 1),
                new Among("use", 10, 1),
                new Among("\u00C3\u00A2se", 10, 1),
                new Among("e\u00C5\u009Fte", -1, 1),
                new Among("\u00C4\u0083\u00C5\u009Fte", -1, 1),
                new Among("eze", -1, 1),
                new Among("ai", -1, 1),
                new Among("eai", 19, 1),
                new Among("iai", 19, 1),
                new Among("sei", -1, 2),
                new Among("e\u00C5\u009Fti", -1, 1),
                new Among("\u00C4\u0083\u00C5\u009Fti", -1, 1),
                new Among("ui", -1, 1),
                new Among("ezi", -1, 1),
                new Among("a\u00C5\u009Fi", -1, 1),
                new Among("se\u00C5\u009Fi", -1, 2),
                new Among("ase\u00C5\u009Fi", 28, 1),
                new Among("sese\u00C5\u009Fi", 28, 2),
                new Among("ise\u00C5\u009Fi", 28, 1),
                new Among("use\u00C5\u009Fi", 28, 1),
                new Among("\u00C3\u00A2se\u00C5\u009Fi", 28, 1),
                new Among("i\u00C5\u009Fi", -1, 1),
                new Among("u\u00C5\u009Fi", -1, 1),
                new Among("\u00C3\u00A2\u00C5\u009Fi", -1, 1),
                new Among("\u00C3\u00A2i", -1, 1),
                new Among("a\u00C5\u00A3i", -1, 2),
                new Among("ea\u00C5\u00A3i", 38, 1),
                new Among("ia\u00C5\u00A3i", 38, 1),
                new Among("e\u00C5\u00A3i", -1, 2),
                new Among("i\u00C5\u00A3i", -1, 2),
                new Among("ar\u00C4\u0083\u00C5\u00A3i", -1, 1),
                new Among("ser\u00C4\u0083\u00C5\u00A3i", -1, 2),
                new Among("aser\u00C4\u0083\u00C5\u00A3i", 44, 1),
                new Among("seser\u00C4\u0083\u00C5\u00A3i", 44, 2),
                new Among("iser\u00C4\u0083\u00C5\u00A3i", 44, 1),
                new Among("user\u00C4\u0083\u00C5\u00A3i", 44, 1),
                new Among("\u00C3\u00A2ser\u00C4\u0083\u00C5\u00A3i", 44, 1),
                new Among("ir\u00C4\u0083\u00C5\u00A3i", -1, 1),
                new Among("ur\u00C4\u0083\u00C5\u00A3i", -1, 1),
                new Among("\u00C3\u00A2r\u00C4\u0083\u00C5\u00A3i", -1, 1),
                new Among("\u00C3\u00A2\u00C5\u00A3i", -1, 2),
                new Among("am", -1, 1),
                new Among("eam", 54, 1),
                new Among("iam", 54, 1),
                new Among("em", -1, 2),
                new Among("asem", 57, 1),
                new Among("sesem", 57, 2),
                new Among("isem", 57, 1),
                new Among("usem", 57, 1),
                new Among("\u00C3\u00A2sem", 57, 1),
                new Among("im", -1, 2),
                new Among("\u00C4\u0083m", -1, 2),
                new Among("ar\u00C4\u0083m", 64, 1),
                new Among("ser\u00C4\u0083m", 64, 2),
                new Among("aser\u00C4\u0083m", 66, 1),
                new Among("seser\u00C4\u0083m", 66, 2),
                new Among("iser\u00C4\u0083m", 66, 1),
                new Among("user\u00C4\u0083m", 66, 1),
                new Among("\u00C3\u00A2ser\u00C4\u0083m", 66, 1),
                new Among("ir\u00C4\u0083m", 64, 1),
                new Among("ur\u00C4\u0083m", 64, 1),
                new Among("\u00C3\u00A2r\u00C4\u0083m", 64, 1),
                new Among("\u00C3\u00A2m", -1, 2),
                new Among("au", -1, 1),
                new Among("eau", 76, 1),
                new Among("iau", 76, 1),
                new Among("indu", -1, 1),
                new Among("\u00C3\u00A2ndu", -1, 1),
                new Among("ez", -1, 1),
                new Among("easc\u00C4\u0083", -1, 1),
                new Among("ar\u00C4\u0083", -1, 1),
                new Among("ser\u00C4\u0083", -1, 2),
                new Among("aser\u00C4\u0083", 84, 1),
                new Among("seser\u00C4\u0083", 84, 2),
                new Among("iser\u00C4\u0083", 84, 1),
                new Among("user\u00C4\u0083", 84, 1),
                new Among("\u00C3\u00A2ser\u00C4\u0083", 84, 1),
                new Among("ir\u00C4\u0083", -1, 1),
                new Among("ur\u00C4\u0083", -1, 1),
                new Among("\u00C3\u00A2r\u00C4\u0083", -1, 1),
                new Among("eaz\u00C4\u0083", -1, 1)
            };

            a_5 = new[] 
            {
                new Among("a", -1, 1),
                new Among("e", -1, 1),
                new Among("ie", 1, 1),
                new Among("i", -1, 1),
                new Among("\u00C4\u0083", -1, 1)
            };

        }



        private bool r_prelude()
        {
            int v_1;
            int v_2;
            int v_3;

            // (, line 31

            // repeat, line 32
            while (true)
            {
                v_1 = cursor;
                while (true) 
                {

                    // goto, line 32
                    v_2 = cursor;

                    // (, line 32
                    if (!(in_grouping(g_v, 97, 259)))
                    {
                        goto lab1;
                    }

                    // [, line 33
                    bra = cursor;

                    // or, line 33
                    v_3 = cursor;

                    // (, line 33

                    // literal, line 33
                    if (!(eq_s(1, "u")))
                    {
                        goto lab3;
                    }

                    // ], line 33
                    ket = cursor;
                    if (!(in_grouping(g_v, 97, 259)))
                    {
                        goto lab3;
                    }

                    // <-, line 33
                    slice_from("U");
                    goto lab2;
                lab3: 
                    cursor = v_3;

                    // (, line 34

                    // literal, line 34
                    if (!(eq_s(1, "i")))
                    {
                        goto lab1;
                    }

                    // ], line 34
                    ket = cursor;
                    if (!(in_grouping(g_v, 97, 259)))
                    {
                        goto lab1;
                    }

                    // <-, line 34
                    slice_from("I");
                lab2: 
                    cursor = v_2;
                    break;
                lab1: 
                    cursor = v_2;
                    if (cursor >= limit)
                    {
                        goto lab0;
                    }
                    cursor++;
                }
                continue;
            lab0: 
                cursor = v_1;
                break;
            }

            return true;
        }

        private bool r_mark_regions()
        {
            int v_1;
            int v_2;
            int v_3;
            int v_6;
            int v_8;

            // (, line 38
            I_pV = limit;
            I_p1 = limit;
            I_p2 = limit;

            // do, line 44
            v_1 = cursor;

            // (, line 44

            // or, line 46
            v_2 = cursor;

            // (, line 45
            if (!(in_grouping(g_v, 97, 259)))
            {
                goto lab2;
            }

            // or, line 45
            v_3 = cursor;

            // (, line 45
            if (!(out_grouping(g_v, 97, 259)))
            {
                goto lab4;
            }
            while (true) 
            {

                // gopast, line 45
                if (!(in_grouping(g_v, 97, 259)))
                {
                    goto lab5;
                }
                break;
            lab5: 
                if (cursor >= limit)
                {
                    goto lab4;
                }
                cursor++;
            }
            goto lab3;
        lab4: 
            cursor = v_3;

            // (, line 45
            if (!(in_grouping(g_v, 97, 259)))
            {
                goto lab2;
            }
            while (true) 
            {

                // gopast, line 45
                if (!(out_grouping(g_v, 97, 259)))
                {
                    goto lab6;
                }
                break;
            lab6: 
                if (cursor >= limit)
                {
                    goto lab2;
                }
                cursor++;
            }
        lab3: 
            goto lab1;
        lab2: 
            cursor = v_2;

            // (, line 47
            if (!(out_grouping(g_v, 97, 259)))
            {
                goto lab0;
            }

            // or, line 47
            v_6 = cursor;

            // (, line 47
            if (!(out_grouping(g_v, 97, 259)))
            {
                goto lab8;
            }
            while (true) 
            {

                // gopast, line 47
                if (!(in_grouping(g_v, 97, 259)))
                {
                    goto lab9;
                }
                break;
            lab9: 
                if (cursor >= limit)
                {
                    goto lab8;
                }
                cursor++;
            }
            goto lab7;
        lab8: 
            cursor = v_6;

            // (, line 47
            if (!(in_grouping(g_v, 97, 259)))
            {
                goto lab0;
            }

            // next, line 47
            if (cursor >= limit)
            {
                goto lab0;
            }
            cursor++;
        lab7: 
        lab1: 

            // setmark pV, line 48
            I_pV = cursor;
        lab0: 
            cursor = v_1;

            // do, line 50
            v_8 = cursor;

            // (, line 50
            while (true) 
            {

                // gopast, line 51
                if (!(in_grouping(g_v, 97, 259)))
                {
                    goto lab11;
                }
                break;
            lab11: 
                if (cursor >= limit)
                {
                    goto lab10;
                }
                cursor++;
            }
            while (true) 
            {

                // gopast, line 51
                if (!(out_grouping(g_v, 97, 259)))
                {
                    goto lab12;
                }
                break;
            lab12: 
                if (cursor >= limit)
                {
                    goto lab10;
                }
                cursor++;
            }

            // setmark p1, line 51
            I_p1 = cursor;
            while (true) 
            {

                // gopast, line 52
                if (!(in_grouping(g_v, 97, 259)))
                {
                    goto lab13;
                }
                break;
            lab13: 
                if (cursor >= limit)
                {
                    goto lab10;
                }
                cursor++;
            }
            while (true) 
            {

                // gopast, line 52
                if (!(out_grouping(g_v, 97, 259)))
                {
                    goto lab14;
                }
                break;
            lab14: 
                if (cursor >= limit)
                {
                    goto lab10;
                }
                cursor++;
            }

            // setmark p2, line 52
            I_p2 = cursor;
        lab10: 
            cursor = v_8;

            return true;
        }

        private bool r_postlude()
        {
            int among_var;
            int v_1;

            // repeat, line 56
            while (true)
            {
                v_1 = cursor;

                // (, line 56

                // [, line 58
                bra = cursor;

                // substring, line 58
                among_var = find_among(a_0, 3);
                if (among_var == 0)
                {
                    goto lab0;
                }

                // ], line 58
                ket = cursor;
                switch (among_var) 
                {
                    case 0:
                    case 1:

                        // (, line 59

                        // <-, line 59
                        slice_from("i");
                        break;
                    case 2:

                        // (, line 60

                        // <-, line 60
                        slice_from("u");
                        break;
                    case 3:

                        // (, line 61

                        // next, line 61
                        if (cursor >= limit)
                        {
                            goto lab0;
                        }
                        cursor++;
                        break;
                }
                continue;
            lab0: 
                cursor = v_1;
                break;
            }

            return true;
        }

        private bool r_RV()
        {
            if (!(I_pV <= cursor))
            {
                return false;
            }

            return true;
        }

        private bool r_R1()
        {
            if (!(I_p1 <= cursor))
            {
                return false;
            }

            return true;
        }

        private bool r_R2()
        {
            if (!(I_p2 <= cursor))
            {
                return false;
            }

            return true;
        }

        private bool r_step_0()
        {
            int among_var;
            int v_1;

            // (, line 72

            // [, line 73
            ket = cursor;

            // substring, line 73
            among_var = find_among_b(a_1, 16);
            if (among_var == 0)
            {
                return false;
            }

            // ], line 73
            bra = cursor;

            // call R1, line 73
            if (!r_R1())
            {
                return false;
            }
            switch (among_var) 
            {
                case 0:
                case 1:

                    // (, line 75

                    // delete, line 75
                    slice_del();
                    break;
                case 2:

                    // (, line 77

                    // <-, line 77
                    slice_from("a");
                    break;
                case 3:

                    // (, line 79

                    // <-, line 79
                    slice_from("e");
                    break;
                case 4:

                    // (, line 81

                    // <-, line 81
                    slice_from("i");
                    break;
                case 5:

                    // (, line 83

                    // not, line 83

                    {
                        v_1 = limit - cursor;

                        // literal, line 83
                        if (!(eq_s_b(2, "ab")))
                        {
                            goto lab0;
                        }
                        return false;
                    lab0: 
                        cursor = limit - v_1;
                    }

                    // <-, line 83
                    slice_from("i");
                    break;
                case 6:

                    // (, line 85

                    // <-, line 85
                    slice_from("at");
                    break;
                case 7:

                    // (, line 87

                    // <-, line 87
                    slice_from("a\u00C5\u00A3i");
                    break;
            }

            return true;
        }

        private bool r_combo_suffix()
        {
            int among_var;
            int v_1;

            // test, line 91
            v_1 = limit - cursor;

            // (, line 91

            // [, line 92
            ket = cursor;

            // substring, line 92
            among_var = find_among_b(a_2, 46);
            if (among_var == 0)
            {
                return false;
            }

            // ], line 92
            bra = cursor;

            // call R1, line 92
            if (!r_R1())
            {
                return false;
            }

            // (, line 92
            switch (among_var) 
            {
                case 0:
                case 1:

                    // (, line 100

                    // <-, line 101
                    slice_from("abil");
                    break;
                case 2:

                    // (, line 103

                    // <-, line 104
                    slice_from("ibil");
                    break;
                case 3:

                    // (, line 106

                    // <-, line 107
                    slice_from("iv");
                    break;
                case 4:

                    // (, line 112

                    // <-, line 113
                    slice_from("ic");
                    break;
                case 5:

                    // (, line 117

                    // <-, line 118
                    slice_from("at");
                    break;
                case 6:

                    // (, line 121

                    // <-, line 122
                    slice_from("it");
                    break;
            }

            // set standard_suffix_removed, line 125
            B_standard_suffix_removed = true;
            cursor = limit - v_1;

            return true;
        }

        private bool r_standard_suffix()
        {
            int among_var;
            int v_1;

            // (, line 129

            // unset standard_suffix_removed, line 130
            B_standard_suffix_removed = false;

            // repeat, line 131
            while (true)
            {
                v_1 = limit - cursor;

                // call combo_suffix, line 131
                if (!r_combo_suffix())
                {
                    goto lab0;
                }
                continue;
            lab0: 
                cursor = limit - v_1;
                break;
            }

            // [, line 132
            ket = cursor;

            // substring, line 132
            among_var = find_among_b(a_3, 62);
            if (among_var == 0)
            {
                return false;
            }

            // ], line 132
            bra = cursor;

            // call R2, line 132
            if (!r_R2())
            {
                return false;
            }

            // (, line 132
            switch (among_var) 
            {
                case 0:
                case 1:

                    // (, line 148

                    // delete, line 149
                    slice_del();
                    break;
                case 2:

                    // (, line 151

                    // literal, line 152
                    if (!(eq_s_b(2, "\u00C5\u00A3")))
                    {
                        return false;
                    }

                    // ], line 152
                    bra = cursor;

                    // <-, line 152
                    slice_from("t");
                    break;
                case 3:

                    // (, line 155

                    // <-, line 156
                    slice_from("ist");
                    break;
            }

            // set standard_suffix_removed, line 160
            B_standard_suffix_removed = true;

            return true;
        }

        private bool r_verb_suffix()
        {
            int among_var;
            int v_1;
            int v_2;
            int v_3;

            // setlimit, line 164
            v_1 = limit - cursor;

            // tomark, line 164
            if (cursor < I_pV)
            {
                return false;
            }
            cursor = I_pV;
            v_2 = limit_backward;
            limit_backward = cursor;
            cursor = limit - v_1;

            // (, line 164

            // [, line 165
            ket = cursor;

            // substring, line 165
            among_var = find_among_b(a_4, 94);
            if (among_var == 0)
            {
                limit_backward = v_2;
                return false;
            }

            // ], line 165
            bra = cursor;
            switch (among_var) 
            {
                case 0:
                case 1:

                    // (, line 200

                    // or, line 200
                    v_3 = limit - cursor;
                    if (!(out_grouping_b(g_v, 97, 259)))
                    {
                        goto lab1;
                    }
                    goto lab0;
                lab1: 
                    cursor = limit - v_3;

                    // literal, line 200
                    if (!(eq_s_b(1, "u")))
                    {
                        limit_backward = v_2;
                        return false;
                    }
                lab0: 

                    // delete, line 200
                    slice_del();
                    break;
                case 2:

                    // (, line 214

                    // delete, line 214
                    slice_del();
                    break;
            }
            limit_backward = v_2;

            return true;
        }

        private bool r_vowel_suffix()
        {
            int among_var;

            // (, line 218

            // [, line 219
            ket = cursor;

            // substring, line 219
            among_var = find_among_b(a_5, 5);
            if (among_var == 0)
            {
                return false;
            }

            // ], line 219
            bra = cursor;

            // call RV, line 219
            if (!r_RV())
            {
                return false;
            }
            switch (among_var) 
            {
                case 0:
                case 1:

                    // (, line 220

                    // delete, line 220
                    slice_del();
                    break;
            }

            return true;
        }

        private bool stem()
        {
            int v_1;
            int v_2;
            int v_3;
            int v_4;
            int v_5;
            int v_6;
            int v_7;
            int v_8;

            // (, line 225

            // do, line 226
            v_1 = cursor;

            // call prelude, line 226
            if (!r_prelude())
            {
                goto lab0;
            }
        lab0: 
            cursor = v_1;

            // do, line 227
            v_2 = cursor;

            // call mark_regions, line 227
            if (!r_mark_regions())
            {
                goto lab1;
            }
        lab1: 
            cursor = v_2;

            // backwards, line 228
            limit_backward = cursor; cursor = limit;

            // (, line 228

            // do, line 229
            v_3 = limit - cursor;

            // call step_0, line 229
            if (!r_step_0())
            {
                goto lab2;
            }
        lab2: 
            cursor = limit - v_3;

            // do, line 230
            v_4 = limit - cursor;

            // call standard_suffix, line 230
            if (!r_standard_suffix())
            {
                goto lab3;
            }
        lab3: 
            cursor = limit - v_4;

            // do, line 231
            v_5 = limit - cursor;

            // (, line 231

            // or, line 231
            v_6 = limit - cursor;

            // Boolean test standard_suffix_removed, line 231
            if (!(B_standard_suffix_removed))
            {
                goto lab6;
            }
            goto lab5;
        lab6: 
            cursor = limit - v_6;

            // call verb_suffix, line 231
            if (!r_verb_suffix())
            {
                goto lab4;
            }
        lab5: 
        lab4: 
            cursor = limit - v_5;

            // do, line 232
            v_7 = limit - cursor;

            // call vowel_suffix, line 232
            if (!r_vowel_suffix())
            {
                goto lab7;
            }
        lab7: 
            cursor = limit - v_7;
            cursor = limit_backward;

            // do, line 234
            v_8 = cursor;

            // call postlude, line 234
            if (!r_postlude())
            {
                goto lab8;
            }
        lab8: 
            cursor = v_8;

            return true;
        }

        protected override bool Process()
        {
            return this.stem();
        }

    }
}

